export default [
  {
    parent: 0,
    value: [],
  },
  {
    parent: 1,
    value: [
      {
        TrangThaiID: 7,
        TenTrangThai: 'Gặp: Không thích vay vì sản phẩm không phù hợp',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 8,
        TenTrangThai: 'Gặp:Từ chối-Phí cao',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 9,
        TenTrangThai: 'Gặp:Từ chối-Không đủ điều kiện',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 10,
        TenTrangThai: 'Gặp-Từ chối-lý do khác',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 11,
        TenTrangThai: 'Không gặp được - Lên lại lịch hẹn',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 12,
        TenTrangThai: 'Không gặp được-Sai địa chỉ',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 13,
        TenTrangThai: 'Không gặp được: yêu cầu gửi email/fax thay cho lịch hẹn',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 14,
        TenTrangThai: 'Không gặp được-Không đồng ý gặp/Hủy',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 15,
        TenTrangThai: 'Không gặp được-Lý do khác',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 16,
        TenTrangThai: 'Đã gặp được khách hàng',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 17,
        TenTrangThai: 'Đang chờ xử lý',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 41,
        TenTrangThai: 'Chuyển cho đối tác',
        Mau: '000000',
        ParentID: 1,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 2,
    value: [
      {
        TrangThaiID: 18,
        TenTrangThai: 'Gặp-Thu thập giấy tờ',
        Mau: '000000',
        ParentID: 2,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 19,
        TenTrangThai: 'Gặp-Giấy tờ đang được xử lý',
        Mau: '000000',
        ParentID: 2,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 3,
    value: [
      {
        TrangThaiID: 20,
        TenTrangThai: 'Gặp-Thu thập giấy tờ đầy đủ',
        Mau: '000000',
        ParentID: 3,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 21,
        TenTrangThai: 'Gặp-Thu thập-Gửi thẩm định',
        Mau: '000000',
        ParentID: 3,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 4,
    value: [
      {
        TrangThaiID: 44,
        TenTrangThai: 'Tạo mới',
        Mau: '000000',
        ParentID: 4,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 6,
    value: [
      {
        TrangThaiID: 22,
        TenTrangThai: 'KH xem xét lại',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 23,
        TenTrangThai: 'Đang thẩm định',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 24,
        TenTrangThai: 'Đang phê duyệt',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 25,
        TenTrangThai: 'Đã nhận hồ sơ',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 26,
        TenTrangThai: 'Đang thu thập chứng từ',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 27,
        TenTrangThai: 'Yêu cầu bổ sung thông tin',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 28,
        TenTrangThai: 'KH từ chối xác nhận qua điện thoại',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 29,
        TenTrangThai: 'KH từ chối xác nhận thực địa',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 30,
        TenTrangThai: 'KH từ chối không vay',
        Mau: 'bd00bd',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 57,
        TenTrangThai: 'Đã gửi',
        Mau: '000000',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 58,
        TenTrangThai: 'Đã có kết quả thẩm định hiện trường',
        Mau: '000000',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 60,
        TenTrangThai: 'Khách hàng ký hợp đồng',
        Mau: '000000',
        ParentID: 6,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 31,
    value: [
      {
        TrangThaiID: 32,
        TenTrangThai: 'Đã hủy do quá thời gian quy định',
        Mau: 'bd00bd',
        ParentID: 31,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 33,
        TenTrangThai: 'Không được duyệt',
        Mau: 'bd00bd',
        ParentID: 31,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 42,
        TenTrangThai: 'Sau yêu cầu bổ sung',
        Mau: '000000',
        ParentID: 31,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 43,
        TenTrangThai: 'Hồ sơ quá thời gian xử lý',
        Mau: '000000',
        ParentID: 31,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 59,
        TenTrangThai: 'Đã hủy',
        Mau: '000000',
        ParentID: 31,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 34,
    value: [
      {
        TrangThaiID: 35,
        TenTrangThai: 'Chờ giải ngân',
        Mau: 'bd00bd',
        ParentID: 34,
        DoiTuongID: 1,
        Tong: 0,
      },
      {
        TrangThaiID: 36,
        TenTrangThai: 'Đã giải ngân',
        Mau: 'bd00bd',
        ParentID: 34,
        DoiTuongID: 1,
        Tong: 0,
      },
    ],
  },
  {
    parent: 47,
    value: [
      {
        TrangThaiID: 48,
        TenTrangThai: 'Hồ sơ bị hủy do không đủ điều kiện / trả về cho Sale',
        Mau: '000000',
        ParentID: 47,
        DoiTuongID: 3,
        Tong: 0,
      },
    ],
  },
  {
    parent: 49,
    value: [
      {
        TrangThaiID: 50,
        TenTrangThai: 'Sale đang nhập',
        Mau: '000000',
        ParentID: 49,
        DoiTuongID: 3,
        Tong: 0,
      },
    ],
  },
  {
    parent: 51,
    value: [
      {
        TrangThaiID: 52,
        TenTrangThai: 'Thẩm định đang xử lý',
        Mau: '000000',
        ParentID: 51,
        DoiTuongID: 3,
        Tong: 0,
      },
    ],
  },
  {
    parent: 53,
    value: [
      {
        TrangThaiID: 54,
        TenTrangThai: 'Đã phê duyệt',
        Mau: '000000',
        ParentID: 53,
        DoiTuongID: 3,
        Tong: 0,
      },
      {
        TrangThaiID: 81,
        TenTrangThai: 'Valid card',
        Mau: '000000',
        ParentID: 53,
        DoiTuongID: 3,
        Tong: 0,
      },
      {
        TrangThaiID: 82,
        TenTrangThai: 'Card is not activated',
        Mau: '000000',
        ParentID: 53,
        DoiTuongID: 3,
        Tong: 0,
      },
      {
        TrangThaiID: 83,
        TenTrangThai: 'Forced PIN change',
        Mau: '000000',
        ParentID: 53,
        DoiTuongID: 3,
        Tong: 0,
      },
      {
        TrangThaiID: 84,
        TenTrangThai: 'Warm card',
        Mau: '000000',
        ParentID: 53,
        DoiTuongID: 3,
        Tong: 0,
      },
    ],
  },
  {
    parent: 55,
    value: [
      {
        TrangThaiID: 56,
        TenTrangThai: 'Hồ sơ bị từ chối',
        Mau: '000000',
        ParentID: 55,
        DoiTuongID: 3,
        Tong: 0,
      },
    ],
  },
  {
    parent: 61,
    value: [],
  },
  {
    parent: 62,
    value: [],
  },
  {
    parent: 63,
    value: [],
  },
  {
    parent: 64,
    value: [],
  },
  {
    parent: 65,
    value: [
      {
        TrangThaiID: 66,
        TenTrangThai: 'Tự động hủy',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 67,
        TenTrangThai: 'Nợ xấu',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 68,
        TenTrangThai: 'Credit Rating',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 69,
        TenTrangThai: 'Khách hàng hủy',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 70,
        TenTrangThai: 'Hồ sơ không đảm bảo',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 71,
        TenTrangThai: 'FV Result',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 72,
        TenTrangThai: 'Negative Info',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 73,
        TenTrangThai: 'Khác',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
      {
        TrangThaiID: 74,
        TenTrangThai: 'Payment Capacity',
        Mau: 'e8461e',
        ParentID: 65,
        DoiTuongID: 7,
        Tong: 0,
      },
    ],
  },
  {
    parent: 76,
    value: [],
  },
  {
    parent: 77,
    value: [],
  },
  {
    parent: 78,
    value: [],
  },
  {
    parent: 79,
    value: [],
  },
  {
    parent: 80,
    value: [],
  },
];
