export default [
  {
    TrangThaiID: 0,
    TenTrangThai: 'Mới tạo',
    Mau: 'ff00ff',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 1,
    TenTrangThai: 'Cuộc hẹn',
    Mau: 'ff00ff',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 2,
    TenTrangThai: 'Gặp',
    Mau: 'bd36c7',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 3,
    TenTrangThai: 'Thu thập giấy tờ',
    Mau: 'b533c4',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 4,
    TenTrangThai: 'Hồ sơ',
    Mau: 'c034d9',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 6,
    TenTrangThai: 'Đang xử lý',
    Mau: 'bd00bd',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 31,
    TenTrangThai: 'Từ chối',
    Mau: 'bd00bd',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 34,
    TenTrangThai: 'Giải ngân',
    Mau: 'bd00bd',
    ParentID: null,
    DoiTuongID: 1,
    Tong: 0,
  },
  {
    TrangThaiID: 47,
    TenTrangThai: 'Hồ sơ bị hủy',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 49,
    TenTrangThai: 'Sale đang nhập',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 51,
    TenTrangThai: 'Thẩm định đang xử lý',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 53,
    TenTrangThai: 'Đã phê duyệt',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 55,
    TenTrangThai: 'Hồ sơ bị từ chối',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 61,
    TenTrangThai: 'Đang nhập liệu',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 62,
    TenTrangThai: 'Kiểm tra hồ sơ',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 63,
    TenTrangThai: 'Hồ sơ trả về',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 64,
    TenTrangThai: 'Hồ sơ bị hủy',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 65,
    TenTrangThai: 'Từ chối',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 76,
    TenTrangThai: 'Đang thẩm định',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 77,
    TenTrangThai: 'Thẩm định duyệt khoản vay',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 78,
    TenTrangThai: 'Khoản vay duyệt chờ giải ngân',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 79,
    TenTrangThai: 'Đã giải ngân',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 80,
    TenTrangThai: 'Lỗi hệ thống',
    Mau: 'd1cb26',
    ParentID: null,
    DoiTuongID: 7,
    Tong: 0,
  },
  {
    TrangThaiID: 85,
    TenTrangThai: 'Hồ sơ hủy',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 3,
    Tong: 0,
  },
  {
    TrangThaiID: 87,
    TenTrangThai: 'Từ chối nhận việc',
    Mau: '6ebd2d',
    ParentID: null,
    DoiTuongID: 10,
    Tong: 0,
  },
  {
    TrangThaiID: 88,
    TenTrangThai: 'Đang làm việc',
    Mau: '49b53f',
    ParentID: null,
    DoiTuongID: 10,
    Tong: 0,
  },
  {
    TrangThaiID: 89,
    TenTrangThai: 'Đã nghỉ việc',
    Mau: '6ebd2d',
    ParentID: null,
    DoiTuongID: 10,
    Tong: 0,
  },
  {
    TrangThaiID: 91,
    TenTrangThai: 'Hồ sơ hủy',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 92,
    TenTrangThai: 'Meeting return chờ bổ sung',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 93,
    TenTrangThai: 'Courier đang xử lý',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 94,
    TenTrangThai: 'Đã tạo app',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 95,
    TenTrangThai: 'App return',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 96,
    TenTrangThai: 'App cancel',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 97,
    TenTrangThai: 'App process',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 98,
    TenTrangThai: 'App reject',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 99,
    TenTrangThai: 'App Approve',
    Mau: '4495cf',
    ParentID: null,
    DoiTuongID: 8,
    Tong: 0,
  },
  {
    TrangThaiID: 119,
    TenTrangThai: 'Đã duyệt',
    Mau: '000000',
    ParentID: null,
    DoiTuongID: 5,
    Tong: 0,
  },
];
