export default [
  {
    TrangThaiID: 0,
    TenTrangThai: 'Mới tạo',
    Mau: 'ff00ff',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 1,
    TenTrangThai: 'Cuộc hẹn',
    Mau: 'ff00ff',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 2,
    TenTrangThai: 'Gặp',
    Mau: 'ff0000',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 3,
    TenTrangThai: 'Thu thập giấy tờ',
    Mau: '009eb3',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 4,
    TenTrangThai: 'Hồ sơ',
    Mau: '48b300',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 6,
    TenTrangThai: 'Đang xử lý',
    Mau: 'bd00bd',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 31,
    TenTrangThai: 'Từ chối',
    Mau: 'bd00bd',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 34,
    TenTrangThai: 'Giải ngân',
    Mau: 'bd00bd',
    DoiTuongID: 1,
    ParentID: null,
  },
  {
    TrangThaiID: 47,
    TenTrangThai: 'Hồ sơ bị hủy',
    Mau: '000000',
    DoiTuongID: 3,
    ParentID: null,
  },
  {
    TrangThaiID: 49,
    TenTrangThai: 'Sale đang nhập',
    Mau: '000000',
    DoiTuongID: 3,
    ParentID: null,
  },
  {
    TrangThaiID: 51,
    TenTrangThai: 'Thẩm định đang xử lý',
    Mau: '000000',
    DoiTuongID: 3,
    ParentID: null,
  },
  {
    TrangThaiID: 53,
    TenTrangThai: 'Đã phê duyệt',
    Mau: '000000',
    DoiTuongID: 3,
    ParentID: null,
  },
  {
    TrangThaiID: 55,
    TenTrangThai: 'Hồ sơ bị từ chối',
    Mau: '000000',
    DoiTuongID: 3,
    ParentID: null,
  },
  {
    TrangThaiID: 61,
    TenTrangThai: 'Data Entry',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 62,
    TenTrangThai: 'Document Check',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 63,
    TenTrangThai: 'Return',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 64,
    TenTrangThai: 'Cancellation',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 65,
    TenTrangThai: 'Rejection',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 76,
    TenTrangThai: 'Under Verification',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 77,
    TenTrangThai: 'Under Approval',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 78,
    TenTrangThai: 'Approved',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 79,
    TenTrangThai: 'Disbursed',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
  {
    TrangThaiID: 80,
    TenTrangThai: 'Database_Checking',
    Mau: 'd1cb26',
    DoiTuongID: 7,
    ParentID: null,
  },
];
