export default [
  {
    MSTinh: 1,
    Mien: 'MIỀN TÂY',
    TenTinh: 'An Giang',
    Quan: [
      {
        MSQuan: 100,
        TenQuanVietTat: 'LX',
        TenQuan: 'Thành phố Long Xuyên',
      },
      {
        MSQuan: 101,
        TenQuanVietTat: 'CD',
        TenQuan: 'Thị xã Châu Đốc',
      },
      {
        MSQuan: 102,
        TenQuanVietTat: 'AP',
        TenQuan: 'An Phú',
      },
      {
        MSQuan: 103,
        TenQuanVietTat: 'TC',
        TenQuan: 'Tân Châu',
      },
      {
        MSQuan: 104,
        TenQuanVietTat: 'PT',
        TenQuan: 'Phú Tân',
      },
      {
        MSQuan: 105,
        TenQuanVietTat: 'TB',
        TenQuan: 'Tịnh Biên',
      },
      {
        MSQuan: 106,
        TenQuanVietTat: 'TT',
        TenQuan: 'Tri Tôn',
      },
      {
        MSQuan: 107,
        TenQuanVietTat: 'CP',
        TenQuan: 'Châu Phú',
      },
      {
        MSQuan: 108,
        TenQuanVietTat: 'CM',
        TenQuan: 'Chợ Mới',
      },
      {
        MSQuan: 109,
        TenQuanVietTat: 'CT',
        TenQuan: 'Châu Thành',
      },
      {
        MSQuan: 110,
        TenQuanVietTat: 'TS',
        TenQuan: 'Thoại Sơn',
      },
    ],
  },
  {
    MSTinh: 2,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Bắc Kạn',
    Quan: [
      {MSQuan: 200, TenQuanVietTat: 'BB', TenQuan: 'Ba Bể'},
      {MSQuan: 201, TenQuanVietTat: 'BK', TenQuan: 'Bắc Kạn'},
      {MSQuan: 202, TenQuanVietTat: 'BT', TenQuan: 'Bạch Thông'},
      {MSQuan: 203, TenQuanVietTat: 'CD', TenQuan: 'Chợ Đồn'},
      {MSQuan: 204, TenQuanVietTat: 'CM', TenQuan: 'Chợ Mới'},
      {MSQuan: 205, TenQuanVietTat: 'NR', TenQuan: 'Na Rì'},
      {MSQuan: 206, TenQuanVietTat: 'NS', TenQuan: 'Ngân Sơn'},
      {MSQuan: 207, TenQuanVietTat: 'PN', TenQuan: 'Pác Nặm'},
    ],
  },
  {
    MSTinh: 3,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Bắc Giang',
    Quan: [
      {MSQuan: 300, TenQuanVietTat: 'BG', TenQuan: 'Bắc Giang'},
      {MSQuan: 301, TenQuanVietTat: 'HH', TenQuan: 'Hiệp Hòa'},
      {MSQuan: 302, TenQuanVietTat: 'LG', TenQuan: 'Lạng Giang'},
      {MSQuan: 303, TenQuanVietTat: 'LN', TenQuan: 'Lục Nam'},
      {MSQuan: 304, TenQuanVietTat: 'LNg', TenQuan: 'Lục Ngạn'},
      {MSQuan: 305, TenQuanVietTat: 'SD', TenQuan: 'Sơn Động'},
      {MSQuan: 306, TenQuanVietTat: 'TY', TenQuan: 'Tân Yên'},
      {MSQuan: 307, TenQuanVietTat: 'VY', TenQuan: 'Việt Yên'},
      {MSQuan: 308, TenQuanVietTat: 'YD', TenQuan: 'Yên Dũng'},
      {MSQuan: 309, TenQuanVietTat: 'YT', TenQuan: 'Yên Thế'},
    ],
  },
  {
    MSTinh: 4,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Bạc Liêu',
    Quan: [
      {MSQuan: 400, TenQuanVietTat: 'BL', TenQuan: 'Thành phố Bạc Liêu'},
      {MSQuan: 401, TenQuanVietTat: 'VL', TenQuan: 'Vĩnh Lợi'},
      {MSQuan: 402, TenQuanVietTat: 'HD', TenQuan: 'Hồng Dân'},
      {MSQuan: 403, TenQuanVietTat: 'GR', TenQuan: 'Giá Rai'},
      {MSQuan: 404, TenQuanVietTat: 'PL', TenQuan: 'Phước Long'},
      {MSQuan: 405, TenQuanVietTat: 'DH', TenQuan: 'Đông Hải'},
      {MSQuan: 406, TenQuanVietTat: 'HB', TenQuan: 'Hoà Bình'},
    ],
  },
  {
    MSTinh: 5,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Bắc Ninh',
    Quan: [
      {MSQuan: 500, TenQuanVietTat: 'BN', TenQuan: 'Bắc Ninh'},
      {MSQuan: 501, TenQuanVietTat: 'GB', TenQuan: 'Gia Bình'},
      {MSQuan: 502, TenQuanVietTat: 'LT', TenQuan: 'Lương Tài'},
      {MSQuan: 503, TenQuanVietTat: 'QV', TenQuan: 'Quế Võ'},
      {MSQuan: 504, TenQuanVietTat: 'TT', TenQuan: 'Thuận Thành'},
      {MSQuan: 505, TenQuanVietTat: 'TD', TenQuan: 'Tiên Du'},
      {MSQuan: 506, TenQuanVietTat: 'TS', TenQuan: 'Từ Sơn'},
      {MSQuan: 507, TenQuanVietTat: 'YP', TenQuan: 'Yên Phong'},
    ],
  },
  {
    MSTinh: 6,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Bến Tre',
    Quan: [
      {MSQuan: 600, TenQuanVietTat: 'TPBT', TenQuan: 'Thành phố Bến Tre'},
      {MSQuan: 601, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 602, TenQuanVietTat: 'CL', TenQuan: 'Chợ Lách'},
      {MSQuan: 603, TenQuanVietTat: 'MCB', TenQuan: 'Mỏ Cày Bắc'},
      {MSQuan: 604, TenQuanVietTat: 'GT', TenQuan: 'Giồng Trôm'},
      {MSQuan: 605, TenQuanVietTat: 'BD', TenQuan: 'Bình Đại'},
      {MSQuan: 606, TenQuanVietTat: 'BT', TenQuan: 'Ba Tri'},
      {MSQuan: 607, TenQuanVietTat: 'TP', TenQuan: 'Thạnh Phú'},
      {MSQuan: 608, TenQuanVietTat: 'MCN', TenQuan: 'Mỏ Cày Nam'},
    ],
  },
  {
    MSTinh: 7,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Bình Định',
    Quan: [
      {MSQuan: 700, TenQuanVietTat: 'AL', TenQuan: 'An Lão'},
      {MSQuan: 701, TenQuanVietTat: 'AN', TenQuan: 'An Nhơn'},
      {MSQuan: 702, TenQuanVietTat: 'HA', TenQuan: 'Hoài Ân'},
      {MSQuan: 703, TenQuanVietTat: 'HN', TenQuan: 'Hoài Nhơn'},
      {MSQuan: 704, TenQuanVietTat: 'PC', TenQuan: 'Phù Cát'},
      {MSQuan: 705, TenQuanVietTat: 'PM', TenQuan: 'Phù Mỹ'},
      {MSQuan: 706, TenQuanVietTat: 'QN', TenQuan: 'Qui Nhơn'},
      {MSQuan: 707, TenQuanVietTat: 'TS', TenQuan: 'Tây Sơn'},
      {MSQuan: 708, TenQuanVietTat: 'TP', TenQuan: 'Tuy Phước'},
      {MSQuan: 709, TenQuanVietTat: 'VC', TenQuan: 'Vân Canh'},
      {MSQuan: 710, TenQuanVietTat: 'VT', TenQuan: 'Vĩnh Thạnh'},
    ],
  },
  {
    MSTinh: 8,
    Mien: 'ĐÔNG NAM BỘ',
    TenTinh: 'Bình Dương',
    Quan: [
      {MSQuan: 800, TenQuanVietTat: 'TDM', TenQuan: 'Thị xã Thủ Dầu Một'},
      {MSQuan: 801, TenQuanVietTat: 'BC', TenQuan: 'Bến Cát'},
      {MSQuan: 802, TenQuanVietTat: 'TU', TenQuan: 'Tân Uyên'},
      {MSQuan: 803, TenQuanVietTat: 'TA', TenQuan: 'Thuận An'},
      {MSQuan: 804, TenQuanVietTat: 'DA', TenQuan: 'Dĩ An'},
      {MSQuan: 805, TenQuanVietTat: 'PG', TenQuan: 'Phú Giáo'},
      {MSQuan: 806, TenQuanVietTat: 'DT', TenQuan: 'Dầu Tiếng'},
    ],
  },
  {
    MSTinh: 9,
    Mien: 'ĐÔNG NAM BỘ',
    TenTinh: 'Bình Phước',
    Quan: [
      {MSQuan: 900, TenQuanVietTat: 'HC', TenQuan: 'Thị xã Đồng Xoài'},
      {MSQuan: 901, TenQuanVietTat: 'TK', TenQuan: 'Đồng Phú'},
      {MSQuan: 902, TenQuanVietTat: 'ST', TenQuan: 'Chơn Thành'},
      {MSQuan: 903, TenQuanVietTat: 'NHS', TenQuan: 'Bình Long'},
      {MSQuan: 904, TenQuanVietTat: 'LC', TenQuan: 'Lộc Ninh'},
      {MSQuan: 905, TenQuanVietTat: 'HV', TenQuan: 'Bù Đốp'},
      {MSQuan: 906, TenQuanVietTat: 'CL', TenQuan: 'Phước Long'},
      {MSQuan: 907, TenQuanVietTat: 'HM', TenQuan: 'Bù Đăng'},
      {MSQuan: 908, TenQuanVietTat: 'LB', TenQuan: 'Hớn Quản'},
      {MSQuan: 909, TenQuanVietTat: 'TL', TenQuan: 'Bù Gia Mập'},
    ],
  },
  {
    MSTinh: 10,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Bình Thuận',
    Quan: [
      {MSQuan: 1000, TenQuanVietTat: 'BB', TenQuan: 'Bắc Bình'},
      {MSQuan: 1001, TenQuanVietTat: 'DL', TenQuan: 'Đức Linh'},
      {MSQuan: 1002, TenQuanVietTat: 'HT', TenQuan: 'Hàm Tân'},
      {MSQuan: 1003, TenQuanVietTat: 'HTB', TenQuan: 'Hàm Thuận Bắc'},
      {MSQuan: 1004, TenQuanVietTat: 'HTN', TenQuan: 'Hàm Thuận Nam'},
      {MSQuan: 1005, TenQuanVietTat: 'LG', TenQuan: 'La Gi'},
      {MSQuan: 1006, TenQuanVietTat: 'PT', TenQuan: 'Phan Thiết'},
      {MSQuan: 1007, TenQuanVietTat: 'PQ', TenQuan: 'Phú Quý'},
      {MSQuan: 1008, TenQuanVietTat: 'TL', TenQuan: 'Tánh Linh'},
      {MSQuan: 1009, TenQuanVietTat: 'TP', TenQuan: 'Tuy Phong'},
    ],
  },
  {
    MSTinh: 11,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Cà Mau',
    Quan: [
      {MSQuan: 1100, TenQuanVietTat: 'CM', TenQuan: 'Thành phố Cà Mau'},
      {MSQuan: 1101, TenQuanVietTat: 'TB', TenQuan: 'Thới Bình'},
      {MSQuan: 1102, TenQuanVietTat: 'UM', TenQuan: 'U Minh'},
      {MSQuan: 1103, TenQuanVietTat: 'TVT', TenQuan: 'Trần Văn Thời'},
      {MSQuan: 1104, TenQuanVietTat: 'CN', TenQuan: 'Cái Nước'},
      {MSQuan: 1105, TenQuanVietTat: 'DD', TenQuan: 'Đầm Dơi'},
      {MSQuan: 1106, TenQuanVietTat: 'NH', TenQuan: 'Ngọc Hiển'},
      {MSQuan: 1107, TenQuanVietTat: 'NC', TenQuan: 'Năm Căn'},
      {MSQuan: 1108, TenQuanVietTat: 'PT', TenQuan: 'Phú Tân'},
    ],
  },
  {
    MSTinh: 12,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Cần Thơ',
    Quan: [
      {MSQuan: 1200, TenQuanVietTat: 'BT', TenQuan: 'Bình Thuỷ'},
      {MSQuan: 1201, TenQuanVietTat: 'CR', TenQuan: 'Cái Răng'},
      {MSQuan: 1202, TenQuanVietTat: 'OM', TenQuan: 'Ô Môn'},
      {MSQuan: 1203, TenQuanVietTat: 'PD', TenQuan: 'Phong Điền'},
      {MSQuan: 1204, TenQuanVietTat: 'CD', TenQuan: 'Cờ Đỏ'},
      {MSQuan: 1205, TenQuanVietTat: 'VT', TenQuan: 'Vĩnh Thạnh'},
      {MSQuan: 1206, TenQuanVietTat: 'TN', TenQuan: 'Thốt Nốt'},
      {MSQuan: 1207, TenQuanVietTat: 'NK', TenQuan: 'Ninh Kiều'},
      {MSQuan: 1208, TenQuanVietTat: 'TL', TenQuan: 'Thới Lai'},
    ],
  },
  {
    MSTinh: 13,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Cao Bằng',
    Quan: [
      {MSQuan: 1300, TenQuanVietTat: 'BL', TenQuan: 'Bảo Lạc'},
      {MSQuan: 1301, TenQuanVietTat: 'BL', TenQuan: 'Bảo Lâm'},
      {MSQuan: 1302, TenQuanVietTat: 'CB', TenQuan: 'Cao Bằng'},
      {MSQuan: 1303, TenQuanVietTat: 'HL', TenQuan: 'Hạ Lang'},
      {MSQuan: 1304, TenQuanVietTat: 'HQ', TenQuan: 'Hà Quảng'},
      {MSQuan: 1305, TenQuanVietTat: 'HA', TenQuan: 'Hòa An'},
      {MSQuan: 1306, TenQuanVietTat: 'NB', TenQuan: 'Nguyên Bình'},
      {MSQuan: 1307, TenQuanVietTat: 'PH', TenQuan: 'Phục Hòa'},
      {MSQuan: 1308, TenQuanVietTat: 'QU', TenQuan: 'Quảng Uyên'},
      {MSQuan: 1309, TenQuanVietTat: 'TA', TenQuan: 'Thạch An'},
      {MSQuan: 1310, TenQuanVietTat: 'TN', TenQuan: 'Thông Nông'},
      {MSQuan: 1311, TenQuanVietTat: 'TL', TenQuan: 'Trà Lĩnh'},
      {MSQuan: 1312, TenQuanVietTat: 'TK', TenQuan: 'Trùng Khánh'},
    ],
  },
  {
    MSTinh: 14,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Đà Nẵng',
    Quan: [
      {MSQuan: 1400, TenQuanVietTat: 'HC', TenQuan: ' Hải Châu'},
      {MSQuan: 1401, TenQuanVietTat: 'TK', TenQuan: 'Thanh Khê'},
      {MSQuan: 1402, TenQuanVietTat: 'ST', TenQuan: 'Sơn Trà'},
      {MSQuan: 1403, TenQuanVietTat: 'NHS', TenQuan: 'Ngũ Hành Sơn'},
      {MSQuan: 1404, TenQuanVietTat: 'LC', TenQuan: 'Liên Chiểu'},
      {MSQuan: 1405, TenQuanVietTat: 'HV', TenQuan: 'Hoà Vang'},
      {MSQuan: 1406, TenQuanVietTat: 'CL', TenQuan: 'Cẩm Lệ'},
    ],
  },
  {
    MSTinh: 15,
    Mien: 'CAO NGUYÊN',
    TenTinh: 'Đăk Lăk',
    Quan: [
      {MSQuan: 1500, TenQuanVietTat: 'BD', TenQuan: 'Buôn Đôn'},
      {MSQuan: 1501, TenQuanVietTat: 'BH', TenQuan: 'Buôn Hồ'},
      {MSQuan: 1502, TenQuanVietTat: 'BMT', TenQuan: 'Buôn Ma Thuột'},
      {MSQuan: 1503, TenQuanVietTat: 'CK', TenQuan: 'Cư Kuin'},
      {MSQuan: 1504, TenQuanVietTat: 'CM', TenQuan: "Cư M'gar"},
      {MSQuan: 1505, TenQuanVietTat: 'EH', TenQuan: "Ea H'leo"},
      {MSQuan: 1506, TenQuanVietTat: 'EK', TenQuan: 'Ea Kar'},
      {MSQuan: 1507, TenQuanVietTat: 'ES', TenQuan: 'Ea Súp'},
      {MSQuan: 1508, TenQuanVietTat: 'KA', TenQuan: 'Krông Ana'},
      {MSQuan: 1509, TenQuanVietTat: 'KBg', TenQuan: 'Krông Bông'},
      {MSQuan: 1510, TenQuanVietTat: 'KB', TenQuan: 'Krông Búk'},
      {MSQuan: 1511, TenQuanVietTat: 'KN', TenQuan: 'Krông Năng'},
      {MSQuan: 1512, TenQuanVietTat: 'KP', TenQuan: 'Krông Pắk'},
      {MSQuan: 1513, TenQuanVietTat: 'L', TenQuan: 'Lắk'},
      {MSQuan: 1514, TenQuanVietTat: 'MD', TenQuan: "M'Đrăk"},
    ],
  },
  {
    MSTinh: 16,
    Mien: 'ĐÔNG NAM BỘ',
    TenTinh: 'Đồng Nai',
    Quan: [
      {MSQuan: 1600, TenQuanVietTat: 'BH', TenQuan: 'Thành phố Biên Hoà'},
      {MSQuan: 1601, TenQuanVietTat: 'VC', TenQuan: 'Vĩnh Cửu'},
      {MSQuan: 1602, TenQuanVietTat: 'TP', TenQuan: 'Tân Phú'},
      {MSQuan: 1603, TenQuanVietTat: 'DQ', TenQuan: 'Định Quán'},
      {MSQuan: 1604, TenQuanVietTat: 'TN', TenQuan: 'Thống Nhất'},
      {MSQuan: 1605, TenQuanVietTat: 'LK', TenQuan: 'Thị xã Long Khánh'},
      {MSQuan: 1606, TenQuanVietTat: 'XL', TenQuan: 'Xuân Lộc'},
      {MSQuan: 1607, TenQuanVietTat: 'LT', TenQuan: 'Long Thành'},
      {MSQuan: 1608, TenQuanVietTat: 'NT', TenQuan: 'Nhơn Trạch'},
      {MSQuan: 1609, TenQuanVietTat: 'TB', TenQuan: 'Trảng Bom'},
      {MSQuan: 1610, TenQuanVietTat: 'CM', TenQuan: 'Cẩm Mỹ'},
    ],
  },
  {
    MSTinh: 17,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Đồng Tháp',
    Quan: [
      {MSQuan: 1700, TenQuanVietTat: 'CL', TenQuan: 'Thành phố Cao Lãnh'},
      {MSQuan: 1701, TenQuanVietTat: 'SD', TenQuan: 'Thị xã Sa Đéc'},
      {MSQuan: 1702, TenQuanVietTat: 'TH', TenQuan: 'Tân Hồng'},
      {MSQuan: 1703, TenQuanVietTat: 'HN', TenQuan: 'Hồng Ngự'},
      {MSQuan: 1704, TenQuanVietTat: 'TN', TenQuan: 'Tam Nông'},
      {MSQuan: 1705, TenQuanVietTat: 'TB', TenQuan: 'Thanh Bình'},
      {MSQuan: 1706, TenQuanVietTat: 'HCL', TenQuan: 'Cao Lãnh'},
      {MSQuan: 1707, TenQuanVietTat: 'LV', TenQuan: 'Lấp Vò'},
      {MSQuan: 1708, TenQuanVietTat: 'TM', TenQuan: 'Tháp Mười'},
      {MSQuan: 1709, TenQuanVietTat: 'LVg', TenQuan: 'Lai Vung'},
      {MSQuan: 1710, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 1711, TenQuanVietTat: 'TXHN', TenQuan: 'Thị xã Hồng Ngự'},
    ],
  },
  {
    MSTinh: 18,
    Mien: 'CAO NGUYÊN',
    TenTinh: 'Gia Lai',
    Quan: [
      {MSQuan: 1800, TenQuanVietTat: 'AK', TenQuan: 'An Khê'},
      {MSQuan: 1801, TenQuanVietTat: 'AP', TenQuan: 'Ayun Pa'},
      {MSQuan: 1802, TenQuanVietTat: 'CP', TenQuan: 'Chư Păh'},
      {MSQuan: 1803, TenQuanVietTat: 'CPr', TenQuan: 'Chư Prông'},
      {MSQuan: 1804, TenQuanVietTat: 'CPu', TenQuan: 'Chư Pưh'},
      {MSQuan: 1805, TenQuanVietTat: 'CS', TenQuan: 'Chư Sê'},
      {MSQuan: 1806, TenQuanVietTat: 'DD', TenQuan: 'Đăk Đoa'},
      {MSQuan: 1807, TenQuanVietTat: 'DP', TenQuan: 'Đắk Pơ'},
      {MSQuan: 1808, TenQuanVietTat: 'DC', TenQuan: 'Đức Cơ'},
      {MSQuan: 1809, TenQuanVietTat: 'IG', TenQuan: 'Ia Grai'},
      {MSQuan: 1810, TenQuanVietTat: 'IP', TenQuan: 'Ia Pa'},
      {MSQuan: 1811, TenQuanVietTat: 'KB', TenQuan: 'KBang'},
      {MSQuan: 1812, TenQuanVietTat: 'KC', TenQuan: 'Kông Chro'},
      {MSQuan: 1813, TenQuanVietTat: 'KP', TenQuan: 'Krông Pa'},
      {MSQuan: 1814, TenQuanVietTat: 'MY', TenQuan: 'Mang Yang'},
      {MSQuan: 1815, TenQuanVietTat: 'PT', TenQuan: 'Phú Thiện'},
      {MSQuan: 1816, TenQuanVietTat: 'PK', TenQuan: 'Pleiku'},
    ],
  },
  {
    MSTinh: 19,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hà Giang',
    Quan: [
      {MSQuan: 1900, TenQuanVietTat: 'BM', TenQuan: 'Bắc Mê'},
      {MSQuan: 1901, TenQuanVietTat: 'BQ', TenQuan: 'Bắc Quang'},
      {MSQuan: 1902, TenQuanVietTat: 'DV', TenQuan: 'Đồng Văn'},
      {MSQuan: 1903, TenQuanVietTat: 'HG', TenQuan: 'Hà Giang'},
      {MSQuan: 1904, TenQuanVietTat: 'HSP', TenQuan: 'Hoàng Su Phì'},
      {MSQuan: 1905, TenQuanVietTat: 'MV', TenQuan: 'Mèo Vạc'},
      {MSQuan: 1906, TenQuanVietTat: 'QB', TenQuan: 'Quản Bạ'},
      {MSQuan: 1907, TenQuanVietTat: 'QB', TenQuan: 'Quang Bình'},
      {MSQuan: 1908, TenQuanVietTat: 'VX', TenQuan: 'Vị Xuyên'},
      {MSQuan: 1909, TenQuanVietTat: 'XM', TenQuan: 'Xín Mần'},
      {MSQuan: 1910, TenQuanVietTat: 'YM', TenQuan: 'Yên Minh'},
    ],
  },
  {
    MSTinh: 20,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hà Nam',
    Quan: [
      {MSQuan: 2000, TenQuanVietTat: 'BL', TenQuan: 'Bình Lục'},
      {MSQuan: 2001, TenQuanVietTat: 'DT', TenQuan: 'Duy Tiên'},
      {MSQuan: 2002, TenQuanVietTat: 'KB', TenQuan: 'Kim Bảng'},
      {MSQuan: 2003, TenQuanVietTat: 'LN', TenQuan: 'Lý Nhân'},
      {MSQuan: 2004, TenQuanVietTat: 'PL', TenQuan: 'Phủ Lý'},
      {MSQuan: 2005, TenQuanVietTat: 'TL', TenQuan: 'Thanh Liêm'},
    ],
  },
  {
    MSTinh: 21,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hà Nội',
    Quan: [
      {MSQuan: 2100, TenQuanVietTat: 'BD', TenQuan: 'Ba Đình'},
      {MSQuan: 2101, TenQuanVietTat: 'HK', TenQuan: 'Hoàn Kiếm'},
      {MSQuan: 2102, TenQuanVietTat: 'HBT', TenQuan: 'Hai Bà Trưng'},
      {MSQuan: 2103, TenQuanVietTat: 'DD', TenQuan: 'Đống Đa'},
      {MSQuan: 2104, TenQuanVietTat: 'TH', TenQuan: 'Tây Hồ'},
      {MSQuan: 2105, TenQuanVietTat: 'CG', TenQuan: 'Cầu Giấy'},
      {MSQuan: 2106, TenQuanVietTat: 'TX', TenQuan: 'Thanh Xuân'},
      {MSQuan: 2107, TenQuanVietTat: 'HM', TenQuan: 'Hoàng Mai'},
      {MSQuan: 2108, TenQuanVietTat: 'LB', TenQuan: 'Long Biên'},
      {MSQuan: 2109, TenQuanVietTat: 'TL', TenQuan: 'Từ Liêm'},
      {MSQuan: 2110, TenQuanVietTat: 'TT', TenQuan: 'Thanh Trì'},
      {MSQuan: 2111, TenQuanVietTat: 'GL', TenQuan: 'Gia Lâm'},
      {MSQuan: 2112, TenQuanVietTat: 'DA', TenQuan: 'Đông Anh'},
      {MSQuan: 2113, TenQuanVietTat: 'SS', TenQuan: 'Sóc Sơn'},
      {MSQuan: 2114, TenQuanVietTat: 'HD', TenQuan: 'Hà Đông'},
      {MSQuan: 2115, TenQuanVietTat: 'ST', TenQuan: 'Thị xã Sơn Tây'},
      {MSQuan: 2116, TenQuanVietTat: 'BV', TenQuan: 'Ba Vì'},
      {MSQuan: 2117, TenQuanVietTat: 'PT', TenQuan: 'Phúc Thọ'},
      {MSQuan: 2118, TenQuanVietTat: 'TTh', TenQuan: 'Thạch Thất'},
      {MSQuan: 2119, TenQuanVietTat: 'QO', TenQuan: 'Quốc Oai'},
      {MSQuan: 2120, TenQuanVietTat: 'CM', TenQuan: 'Chương Mỹ'},
      {MSQuan: 2121, TenQuanVietTat: 'DP', TenQuan: 'Đan Phượng'},
      {MSQuan: 2122, TenQuanVietTat: 'HDc', TenQuan: 'Hoài Đức'},
      {MSQuan: 2123, TenQuanVietTat: 'TO', TenQuan: 'Thanh Oai'},
      {MSQuan: 2124, TenQuanVietTat: 'MD', TenQuan: 'Mỹ Đức'},
      {MSQuan: 2125, TenQuanVietTat: 'UH', TenQuan: 'Ứng Hoà'},
      {MSQuan: 2126, TenQuanVietTat: 'TTi', TenQuan: 'Thường Tín'},
      {MSQuan: 2127, TenQuanVietTat: 'PX', TenQuan: 'Phú Xuyên'},
      {MSQuan: 2128, TenQuanVietTat: 'ML', TenQuan: 'Mê Linh'},
    ],
  },
  {
    MSTinh: 22,
    Mien: 'MIỀN BẮC',
    TenTinh: 'HÀ TÂY',
    Quan: [],
  },
  {
    MSTinh: 23,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Hà Tĩnh',
    Quan: [
      {MSQuan: 2300, TenQuanVietTat: 'CX', TenQuan: 'Cẩm Xuyên'},
      {MSQuan: 2301, TenQuanVietTat: 'CL', TenQuan: 'Can Lộc'},
      {MSQuan: 2302, TenQuanVietTat: 'DT', TenQuan: 'Đức Thọ'},
      {MSQuan: 2303, TenQuanVietTat: 'HT', TenQuan: 'Hà Tĩnh'},
      {MSQuan: 2304, TenQuanVietTat: 'HL', TenQuan: 'Hồng Lĩnh'},
      {MSQuan: 2305, TenQuanVietTat: 'HK', TenQuan: 'Hương Khê'},
      {MSQuan: 2306, TenQuanVietTat: 'HS', TenQuan: 'Hương Sơn'},
      {MSQuan: 2307, TenQuanVietTat: 'KA', TenQuan: 'Kỳ Anh'},
      {MSQuan: 2308, TenQuanVietTat: 'LH', TenQuan: 'Lộc Hà'},
      {MSQuan: 2309, TenQuanVietTat: 'NX', TenQuan: 'Nghi Xuân'},
      {MSQuan: 2310, TenQuanVietTat: 'TH', TenQuan: 'Thạch Hà'},
      {MSQuan: 2311, TenQuanVietTat: 'VQ', TenQuan: 'Vũ Quang'},
    ],
  },
  {
    MSTinh: 24,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hải Dương',
    Quan: [
      {MSQuan: 2400, TenQuanVietTat: 'BG', TenQuan: 'Bình Giang'},
      {MSQuan: 2401, TenQuanVietTat: 'CG', TenQuan: 'Cẩm Giàng'},
      {MSQuan: 2402, TenQuanVietTat: 'CL', TenQuan: 'Chí Linh'},
      {MSQuan: 2403, TenQuanVietTat: 'GL', TenQuan: 'Gia Lộc'},
      {MSQuan: 2404, TenQuanVietTat: 'HD', TenQuan: 'Hải Dương'},
      {MSQuan: 2405, TenQuanVietTat: 'KT', TenQuan: 'Kim Thành'},
      {MSQuan: 2406, TenQuanVietTat: 'KM', TenQuan: 'Kinh Môn'},
      {MSQuan: 2407, TenQuanVietTat: 'NS', TenQuan: 'Nam Sách'},
      {MSQuan: 2408, TenQuanVietTat: 'NG', TenQuan: 'Ninh Giang'},
      {MSQuan: 2409, TenQuanVietTat: 'TH', TenQuan: 'Thanh Hà'},
      {MSQuan: 2410, TenQuanVietTat: 'TM', TenQuan: 'Thanh Miện'},
      {MSQuan: 2411, TenQuanVietTat: 'TK', TenQuan: 'Tứ Kỳ'},
    ],
  },
  {
    MSTinh: 25,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hải Phòng',
    Quan: [
      {MSQuan: 2500, TenQuanVietTat: 'AD', TenQuan: 'An Dương'},
      {MSQuan: 2501, TenQuanVietTat: 'AL', TenQuan: 'An Lão'},
      {MSQuan: 2502, TenQuanVietTat: 'BLV', TenQuan: 'Bạch Long Vĩ'},
      {MSQuan: 2503, TenQuanVietTat: 'CH', TenQuan: 'Cát Hải'},
      {MSQuan: 2504, TenQuanVietTat: 'DS', TenQuan: 'Đồ Sơn'},
      {MSQuan: 2505, TenQuanVietTat: 'DK', TenQuan: 'Dương Kinh'},
      {MSQuan: 2506, TenQuanVietTat: 'HA', TenQuan: 'Hải An'},
      {MSQuan: 2507, TenQuanVietTat: 'HB', TenQuan: 'Hồng Bàng'},
      {MSQuan: 2508, TenQuanVietTat: 'KA', TenQuan: 'Kiến An'},
      {MSQuan: 2509, TenQuanVietTat: 'KT', TenQuan: 'Kiến Thụy'},
      {MSQuan: 2510, TenQuanVietTat: 'LC', TenQuan: 'Lê Chân'},
      {MSQuan: 2511, TenQuanVietTat: 'NQ', TenQuan: 'Ngô Quyền'},
      {MSQuan: 2512, TenQuanVietTat: 'TN', TenQuan: 'Thuỷ Nguyên'},
      {MSQuan: 2513, TenQuanVietTat: 'TL', TenQuan: 'Tiên Lãng'},
      {MSQuan: 2514, TenQuanVietTat: 'VB', TenQuan: 'Vĩnh Bảo'},
    ],
  },
  {
    MSTinh: 26,
    Mien: 'MIỀN BẮC',
    TenTinh: 'HÒA BÌNH',
    Quan: [
      {MSQuan: 2600, TenQuanVietTat: 'CP', TenQuan: 'Cao Phong'},
      {MSQuan: 2601, TenQuanVietTat: 'DB', TenQuan: 'Đà Bắc'},
      {MSQuan: 2602, TenQuanVietTat: 'HB', TenQuan: 'Hoà Bình'},
      {MSQuan: 2603, TenQuanVietTat: 'KB', TenQuan: 'Kim Bôi'},
      {MSQuan: 2604, TenQuanVietTat: 'KS', TenQuan: 'Kỳ Sơn'},
      {MSQuan: 2605, TenQuanVietTat: 'LS', TenQuan: 'Lạc Sơn'},
      {MSQuan: 2606, TenQuanVietTat: 'LT', TenQuan: 'Lạc Thủy'},
      {MSQuan: 2607, TenQuanVietTat: 'LgS', TenQuan: 'Lương Sơn'},
      {MSQuan: 2608, TenQuanVietTat: 'MC', TenQuan: 'Mai Châu'},
      {MSQuan: 2609, TenQuanVietTat: 'TL', TenQuan: 'Tân Lạc'},
      {MSQuan: 2610, TenQuanVietTat: 'YT', TenQuan: 'Yên Thủy'},
    ],
  },
  {
    MSTinh: 27,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Thừa Thiên-Huế',
    Quan: [
      {MSQuan: 2700, TenQuanVietTat: 'AL', TenQuan: 'A Lưới'},
      {MSQuan: 2701, TenQuanVietTat: 'H', TenQuan: 'Huế'},
      {MSQuan: 2702, TenQuanVietTat: 'HT', TenQuan: 'Hương Thủy'},
      {MSQuan: 2703, TenQuanVietTat: 'HrT', TenQuan: 'Hương Trà'},
      {MSQuan: 2704, TenQuanVietTat: 'ND', TenQuan: 'Nam Đông'},
      {MSQuan: 2705, TenQuanVietTat: 'PD', TenQuan: 'Phong Điền'},
      {MSQuan: 2706, TenQuanVietTat: 'PL', TenQuan: 'Phú Lộc'},
      {MSQuan: 2707, TenQuanVietTat: 'PV', TenQuan: 'Phú Vang'},
      {MSQuan: 2708, TenQuanVietTat: 'QD', TenQuan: 'Quảng Điền'},
    ],
  },
  {
    MSTinh: 28,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Hưng Yên',
    Quan: [
      {MSQuan: 2800, TenQuanVietTat: 'AT', TenQuan: 'Ân Thi'},
      {MSQuan: 2801, TenQuanVietTat: 'HY', TenQuan: 'Hưng Yên'},
      {MSQuan: 2802, TenQuanVietTat: 'KC', TenQuan: 'Khoái Châu'},
      {MSQuan: 2803, TenQuanVietTat: 'KD', TenQuan: 'Kim Động'},
      {MSQuan: 2804, TenQuanVietTat: 'MH', TenQuan: 'Mỹ Hào'},
      {MSQuan: 2805, TenQuanVietTat: 'PC', TenQuan: 'Phù Cừ'},
      {MSQuan: 2806, TenQuanVietTat: 'TL', TenQuan: 'Tiên Lữ'},
      {MSQuan: 2807, TenQuanVietTat: 'VG', TenQuan: 'Văn Giang'},
      {MSQuan: 2808, TenQuanVietTat: 'VL', TenQuan: 'Văn Lâm'},
      {MSQuan: 2809, TenQuanVietTat: 'YM', TenQuan: 'Yên Mỹ'},
    ],
  },
  {
    MSTinh: 29,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Khánh Hoà',
    Quan: [
      {MSQuan: 2900, TenQuanVietTat: 'CL', TenQuan: 'Cam Lâm'},
      {MSQuan: 2901, TenQuanVietTat: 'CR', TenQuan: 'Cam Ranh'},
      {MSQuan: 2902, TenQuanVietTat: 'DK', TenQuan: 'Diên Khánh'},
      {MSQuan: 2903, TenQuanVietTat: 'KS', TenQuan: 'Khánh Sơn'},
      {MSQuan: 2904, TenQuanVietTat: 'KV', TenQuan: 'Khánh Vĩnh'},
      {MSQuan: 2905, TenQuanVietTat: 'NT', TenQuan: 'Nha Trang'},
      {MSQuan: 2906, TenQuanVietTat: 'NH', TenQuan: 'Ninh Hòa'},
      {MSQuan: 2907, TenQuanVietTat: 'TS', TenQuan: 'Trường Sa'},
      {MSQuan: 2908, TenQuanVietTat: 'VN', TenQuan: 'Vạn Ninh'},
    ],
  },
  {
    MSTinh: 30,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Kiên Giang',
    Quan: [
      {MSQuan: 3000, TenQuanVietTat: 'RG', TenQuan: 'Thành phố Rạch Giá'},
      {MSQuan: 3001, TenQuanVietTat: 'HT', TenQuan: 'Thị xã Hà Tiên'},
      {MSQuan: 3002, TenQuanVietTat: 'KL', TenQuan: 'Kiên Lương'},
      {MSQuan: 3003, TenQuanVietTat: 'HD', TenQuan: 'Hòn Đất'},
      {MSQuan: 3004, TenQuanVietTat: 'TH', TenQuan: 'Tân Hiệp'},
      {MSQuan: 3005, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 3006, TenQuanVietTat: 'GR', TenQuan: 'Giồng Riềng'},
      {MSQuan: 3007, TenQuanVietTat: 'GQ', TenQuan: 'Gò Quao'},
      {MSQuan: 3008, TenQuanVietTat: 'AB', TenQuan: 'An Biên'},
      {MSQuan: 3009, TenQuanVietTat: 'AM', TenQuan: 'An Minh'},
      {MSQuan: 3010, TenQuanVietTat: 'VT', TenQuan: 'Vĩnh Thuận'},
      {MSQuan: 3011, TenQuanVietTat: 'PQ', TenQuan: 'đảo Phú Quốc'},
      {MSQuan: 3012, TenQuanVietTat: 'KH', TenQuan: 'Kiên Hải'},
      {MSQuan: 3013, TenQuanVietTat: 'UMT', TenQuan: 'U Minh Thượng'},
      {MSQuan: 3014, TenQuanVietTat: 'GT', TenQuan: 'Giang Thành'},
    ],
  },
  {
    MSTinh: 31,
    Mien: 'CAO NGUYÊN',
    TenTinh: 'Kon Tum',
    Quan: [
      {MSQuan: 3100, TenQuanVietTat: 'DG', TenQuan: 'Đắk Glei'},
      {MSQuan: 3101, TenQuanVietTat: 'DH', TenQuan: 'Đắk Hà'},
      {MSQuan: 3102, TenQuanVietTat: 'DT', TenQuan: 'Đăk Tô'},
      {MSQuan: 3103, TenQuanVietTat: 'KP', TenQuan: 'Kon Plông'},
      {MSQuan: 3104, TenQuanVietTat: 'KR', TenQuan: 'Kon Rẫy'},
      {MSQuan: 3105, TenQuanVietTat: 'KT', TenQuan: 'Kon Tum'},
      {MSQuan: 3106, TenQuanVietTat: 'NH', TenQuan: 'Ngọc Hồi'},
      {MSQuan: 3107, TenQuanVietTat: 'ST', TenQuan: 'Sa Thầy'},
      {MSQuan: 3108, TenQuanVietTat: 'TMR', TenQuan: 'Tu Mơ Rông'},
    ],
  },
  {
    MSTinh: 32,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Lai Châu',
    Quan: [
      {MSQuan: 3200, TenQuanVietTat: 'LC', TenQuan: 'Lai Châu'},
      {MSQuan: 3201, TenQuanVietTat: 'MT', TenQuan: 'Mường Tè'},
      {MSQuan: 3202, TenQuanVietTat: 'NN', TenQuan: 'Nậm Nhùn'},
      {MSQuan: 3203, TenQuanVietTat: 'PT', TenQuan: 'Phong Thổ'},
      {MSQuan: 3204, TenQuanVietTat: 'SH', TenQuan: 'Sìn Hồ'},
      {MSQuan: 3205, TenQuanVietTat: 'TD', TenQuan: 'Tam Đường'},
      {MSQuan: 3206, TenQuanVietTat: 'TU', TenQuan: 'Tân Uyên'},
      {MSQuan: 3207, TenQuanVietTat: 'ThU', TenQuan: 'Than Uyên'},
    ],
  },
  {
    MSTinh: 33,
    Mien: 'CAO NGUYÊN',
    TenTinh: 'Lâm Đồng',
    Quan: [
      {MSQuan: 3300, TenQuanVietTat: 'BLm', TenQuan: 'Bảo Lâm'},
      {MSQuan: 3301, TenQuanVietTat: 'BL', TenQuan: 'Bảo Lộc'},
      {MSQuan: 3302, TenQuanVietTat: 'CT', TenQuan: 'Cát Tiên'},
      {MSQuan: 3303, TenQuanVietTat: 'DH', TenQuan: 'Đạ Huoai'},
      {MSQuan: 3304, TenQuanVietTat: 'DL', TenQuan: 'Đà Lạt'},
      {MSQuan: 3305, TenQuanVietTat: 'DT', TenQuan: 'Đạ Tẻh'},
      {MSQuan: 3306, TenQuanVietTat: 'DR', TenQuan: 'Đam Rông'},
      {MSQuan: 3307, TenQuanVietTat: 'DLn', TenQuan: 'Di Linh'},
      {MSQuan: 3308, TenQuanVietTat: 'DD', TenQuan: 'Đơn Dương'},
      {MSQuan: 3309, TenQuanVietTat: 'DTr', TenQuan: 'Đức Trọng'},
      {MSQuan: 3310, TenQuanVietTat: 'LD', TenQuan: 'Lạc Dương'},
      {MSQuan: 3311, TenQuanVietTat: 'LH', TenQuan: 'Lâm Hà'},
    ],
  },
  {
    MSTinh: 34,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Lạng Sơn',
    Quan: [
      {MSQuan: 3400, TenQuanVietTat: 'BS', TenQuan: 'Bắc Sơn'},
      {MSQuan: 3401, TenQuanVietTat: 'BG', TenQuan: 'Bình Gia'},
      {MSQuan: 3402, TenQuanVietTat: 'CL', TenQuan: 'Cao Lộc'},
      {MSQuan: 3403, TenQuanVietTat: 'CLg', TenQuan: 'Chi Lăng'},
      {MSQuan: 3404, TenQuanVietTat: 'DL', TenQuan: 'Đình Lập'},
      {MSQuan: 3405, TenQuanVietTat: 'HL', TenQuan: 'Hữu Lũng'},
      {MSQuan: 3406, TenQuanVietTat: 'LS', TenQuan: 'Lạng Sơn'},
      {MSQuan: 3407, TenQuanVietTat: 'LB', TenQuan: 'Lộc Bình'},
      {MSQuan: 3408, TenQuanVietTat: 'TD', TenQuan: 'Tràng Định'},
      {MSQuan: 3409, TenQuanVietTat: 'VL', TenQuan: 'Vãn Lãng'},
      {MSQuan: 3410, TenQuanVietTat: 'VQ', TenQuan: 'Văn Quan'},
    ],
  },
  {
    MSTinh: 35,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Lào Cai',
    Quan: [
      {MSQuan: 3500, TenQuanVietTat: 'BH', TenQuan: 'Bắc Hà'},
      {MSQuan: 3501, TenQuanVietTat: 'BT', TenQuan: 'Bảo Thắng'},
      {MSQuan: 3502, TenQuanVietTat: 'BY', TenQuan: 'Bảo Yên'},
      {MSQuan: 3503, TenQuanVietTat: 'BX', TenQuan: 'Bát Xát'},
      {MSQuan: 3504, TenQuanVietTat: 'LC', TenQuan: 'Lào Cai'},
      {MSQuan: 3505, TenQuanVietTat: 'MK', TenQuan: 'Mường Khương'},
      {MSQuan: 3506, TenQuanVietTat: 'SP', TenQuan: 'Sa Pa'},
      {MSQuan: 3507, TenQuanVietTat: 'SMC', TenQuan: 'Si Ma Cai'},
      {MSQuan: 3508, TenQuanVietTat: 'VB', TenQuan: 'Văn Bàn'},
    ],
  },
  {
    MSTinh: 36,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Long An',
    Quan: [
      {MSQuan: 3600, TenQuanVietTat: 'TA', TenQuan: 'Thành phố Tân An'},
      {MSQuan: 3601, TenQuanVietTat: 'VH', TenQuan: 'Vĩnh Hưng'},
      {MSQuan: 3602, TenQuanVietTat: 'MH', TenQuan: 'Mộc Hoá'},
      {MSQuan: 3603, TenQuanVietTat: 'TT', TenQuan: 'Tân Thạnh'},
      {MSQuan: 3604, TenQuanVietTat: 'TH', TenQuan: 'Thạnh Hoá'},
      {MSQuan: 3605, TenQuanVietTat: 'DH', TenQuan: 'Đức Huệ'},
      {MSQuan: 3606, TenQuanVietTat: 'DHo', TenQuan: 'Đức Hoà'},
      {MSQuan: 3607, TenQuanVietTat: 'BL', TenQuan: 'Bến Lức'},
      {MSQuan: 3608, TenQuanVietTat: 'TTu', TenQuan: 'Thủ Thừa'},
      {MSQuan: 3609, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 3610, TenQuanVietTat: 'TTr', TenQuan: 'Tân Trụ'},
      {MSQuan: 3611, TenQuanVietTat: 'CD', TenQuan: 'Cần Đước'},
      {MSQuan: 3612, TenQuanVietTat: 'CG', TenQuan: 'Cần Giuộc'},
      {MSQuan: 3613, TenQuanVietTat: 'THu', TenQuan: 'Tân Hưng'},
    ],
  },
  {
    MSTinh: 37,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Nam Định',
    Quan: [
      {MSQuan: 3700, TenQuanVietTat: 'GT', TenQuan: 'Giao Thủy'},
      {MSQuan: 3701, TenQuanVietTat: 'HH', TenQuan: 'Hải Hậu'},
      {MSQuan: 3702, TenQuanVietTat: 'ML', TenQuan: 'Mỹ Lộc'},
      {MSQuan: 3703, TenQuanVietTat: 'ND', TenQuan: 'Nam Định'},
      {MSQuan: 3704, TenQuanVietTat: 'NT', TenQuan: 'Nam Trực'},
      {MSQuan: 3705, TenQuanVietTat: 'NH', TenQuan: 'Nghĩa Hưng'},
      {MSQuan: 3706, TenQuanVietTat: 'TN', TenQuan: 'Trực Ninh'},
      {MSQuan: 3707, TenQuanVietTat: 'VB', TenQuan: 'Vụ Bản'},
      {MSQuan: 3708, TenQuanVietTat: 'XT', TenQuan: 'Xuân Trường'},
      {MSQuan: 3709, TenQuanVietTat: 'YY', TenQuan: 'Ý Yên'},
    ],
  },
  {
    MSTinh: 38,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Nghệ An',
    Quan: [
      {MSQuan: 3800, TenQuanVietTat: 'AS', TenQuan: 'Anh Sơn'},
      {MSQuan: 3801, TenQuanVietTat: 'CC', TenQuan: 'Con Cuông'},
      {MSQuan: 3802, TenQuanVietTat: 'CL', TenQuan: 'Cửa Lò'},
      {MSQuan: 3803, TenQuanVietTat: 'DC', TenQuan: 'Diễn Châu'},
      {MSQuan: 3804, TenQuanVietTat: 'DL', TenQuan: 'Đô Lương'},
      {MSQuan: 3805, TenQuanVietTat: 'HM', TenQuan: 'Hoàng Mai'},
      {MSQuan: 3806, TenQuanVietTat: 'HN', TenQuan: 'Hưng Nguyên'},
      {MSQuan: 3807, TenQuanVietTat: 'KS', TenQuan: 'Kỳ Sơn'},
      {MSQuan: 3808, TenQuanVietTat: 'ND', TenQuan: 'Nam Đàn'},
      {MSQuan: 3809, TenQuanVietTat: 'NL', TenQuan: 'Nghi Lộc'},
      {MSQuan: 3810, TenQuanVietTat: 'NgD', TenQuan: 'Nghĩa Đàn'},
      {MSQuan: 3811, TenQuanVietTat: 'QP', TenQuan: 'Quế Phong'},
      {MSQuan: 3812, TenQuanVietTat: 'QC', TenQuan: 'Quỳ Châu'},
      {MSQuan: 3813, TenQuanVietTat: 'QH', TenQuan: 'Quỳ Hợp'},
      {MSQuan: 3814, TenQuanVietTat: 'QL', TenQuan: 'Quỳnh Lưu'},
      {MSQuan: 3815, TenQuanVietTat: 'TK', TenQuan: 'Tân Kỳ'},
      {MSQuan: 3816, TenQuanVietTat: 'TH', TenQuan: 'Thái Hòa'},
      {MSQuan: 3817, TenQuanVietTat: 'TC', TenQuan: 'Thanh Chương'},
      {MSQuan: 3818, TenQuanVietTat: 'TD', TenQuan: 'Tương Dương'},
      {MSQuan: 3819, TenQuanVietTat: 'V', TenQuan: 'Vinh'},
      {MSQuan: 3820, TenQuanVietTat: 'YT', TenQuan: 'Yên Thành'},
    ],
  },
  {
    MSTinh: 39,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Ninh Bình',
    Quan: [
      {MSQuan: 3900, TenQuanVietTat: 'GV', TenQuan: 'Gia Viễn'},
      {MSQuan: 3901, TenQuanVietTat: 'HL', TenQuan: 'Hoa Lư'},
      {MSQuan: 3902, TenQuanVietTat: 'KS', TenQuan: 'Kim Sơn'},
      {MSQuan: 3903, TenQuanVietTat: 'NQ', TenQuan: 'Nho Quan'},
      {MSQuan: 3904, TenQuanVietTat: 'NB', TenQuan: 'Ninh Bình'},
      {MSQuan: 3905, TenQuanVietTat: 'TD', TenQuan: 'Tam Điệp'},
      {MSQuan: 3906, TenQuanVietTat: 'YK', TenQuan: 'Yên Khánh'},
      {MSQuan: 3907, TenQuanVietTat: 'YM', TenQuan: 'Yên Mô'},
    ],
  },
  {
    MSTinh: 40,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Ninh Thuận',
    Quan: [
      {MSQuan: 4000, TenQuanVietTat: 'BA', TenQuan: 'Bác Ái'},
      {MSQuan: 4001, TenQuanVietTat: 'NH', TenQuan: 'Ninh Hải'},
      {MSQuan: 4002, TenQuanVietTat: 'NP', TenQuan: 'Ninh Phước'},
      {MSQuan: 4003, TenQuanVietTat: 'NS', TenQuan: 'Ninh Sơn'},
      {MSQuan: 4004, TenQuanVietTat: 'PRT', TenQuan: 'Phan Rang-Tháp Chàm'},
      {MSQuan: 4005, TenQuanVietTat: 'TB', TenQuan: 'Thuận Bắc'},
      {MSQuan: 4006, TenQuanVietTat: 'TN', TenQuan: 'Thuận Nam'},
    ],
  },
  {
    MSTinh: 41,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Phú Thọ',
    Quan: [
      {MSQuan: 4100, TenQuanVietTat: 'CK', TenQuan: 'Cẩm Khê'},
      {MSQuan: 4101, TenQuanVietTat: 'DH', TenQuan: 'Đoan Hùng'},
      {MSQuan: 4102, TenQuanVietTat: 'HH', TenQuan: 'Hạ Hòa'},
      {MSQuan: 4103, TenQuanVietTat: 'LT', TenQuan: 'Lâm Thao'},
      {MSQuan: 4104, TenQuanVietTat: 'PN', TenQuan: 'Phù Ninh'},
      {MSQuan: 4105, TenQuanVietTat: 'PT', TenQuan: 'Phú Thọ'},
      {MSQuan: 4106, TenQuanVietTat: 'TN', TenQuan: 'Tam Nông'},
      {MSQuan: 4107, TenQuanVietTat: 'TS', TenQuan: 'Tân Sơn'},
      {MSQuan: 4108, TenQuanVietTat: 'TB', TenQuan: 'Thanh Ba'},
      {MSQuan: 4109, TenQuanVietTat: 'TS', TenQuan: 'Thanh Sơn'},
      {MSQuan: 4110, TenQuanVietTat: 'TT', TenQuan: 'Thanh Thủy'},
      {MSQuan: 4111, TenQuanVietTat: 'VT', TenQuan: 'Việt Trì'},
      {MSQuan: 4112, TenQuanVietTat: 'YL', TenQuan: 'Yên Lập'},
    ],
  },
  {
    MSTinh: 42,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Phú Yên',
    Quan: [
      {MSQuan: 4200, TenQuanVietTat: 'DH', TenQuan: 'Đông Hòa'},
      {MSQuan: 4201, TenQuanVietTat: 'DX', TenQuan: 'Đồng Xuân'},
      {MSQuan: 4202, TenQuanVietTat: 'PH', TenQuan: 'Phú Hòa'},
      {MSQuan: 4203, TenQuanVietTat: 'SH', TenQuan: 'Sơn Hòa'},
      {MSQuan: 4204, TenQuanVietTat: 'SC', TenQuan: 'Sông Cầu'},
      {MSQuan: 4205, TenQuanVietTat: 'SgH', TenQuan: 'Sông Hinh'},
      {MSQuan: 4206, TenQuanVietTat: 'TH', TenQuan: 'Tây Hòa'},
      {MSQuan: 4207, TenQuanVietTat: 'TA', TenQuan: 'Tuy An'},
      {MSQuan: 4208, TenQuanVietTat: 'TuH', TenQuan: 'Tuy Hòa'},
    ],
  },
  {
    MSTinh: 43,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Quảng Bình',
    Quan: [
      {MSQuan: 4300, TenQuanVietTat: 'BT', TenQuan: 'Bố Trạch'},
      {MSQuan: 4301, TenQuanVietTat: 'DH', TenQuan: 'Đồng Hới'},
      {MSQuan: 4302, TenQuanVietTat: 'LT', TenQuan: 'Lệ Thủy'},
      {MSQuan: 4303, TenQuanVietTat: 'MH', TenQuan: 'Minh Hóa'},
      {MSQuan: 4304, TenQuanVietTat: 'QN', TenQuan: 'Quảng Ninh'},
      {MSQuan: 4305, TenQuanVietTat: 'QT', TenQuan: 'Quảng Trạch'},
      {MSQuan: 4306, TenQuanVietTat: 'TH', TenQuan: 'Tuyên Hóa'},
    ],
  },
  {
    MSTinh: 44,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Quảng Nam',
    Quan: [
      {MSQuan: 4400, TenQuanVietTat: 'BTM', TenQuan: 'Bắc Trà My'},
      {MSQuan: 4401, TenQuanVietTat: 'DL', TenQuan: 'Đại Lộc'},
      {MSQuan: 4402, TenQuanVietTat: 'DB', TenQuan: 'Điện Bàn'},
      {MSQuan: 4403, TenQuanVietTat: 'DG', TenQuan: 'Đông Giang'},
      {MSQuan: 4404, TenQuanVietTat: 'DX', TenQuan: 'Duy Xuyên'},
      {MSQuan: 4405, TenQuanVietTat: 'HD', TenQuan: 'Hiệp Đức'},
      {MSQuan: 4406, TenQuanVietTat: 'HA', TenQuan: 'Hội An'},
      {MSQuan: 4407, TenQuanVietTat: 'NG', TenQuan: 'Nam Giang'},
      {MSQuan: 4408, TenQuanVietTat: 'NTM', TenQuan: 'Nam Trà My'},
      {MSQuan: 4409, TenQuanVietTat: 'NS', TenQuan: 'Nông Sơn'},
      {MSQuan: 4410, TenQuanVietTat: 'NT', TenQuan: 'Núi Thành'},
      {MSQuan: 4411, TenQuanVietTat: 'PN', TenQuan: 'Phú Ninh'},
      {MSQuan: 4412, TenQuanVietTat: 'PS', TenQuan: 'Phước Sơn'},
      {MSQuan: 4413, TenQuanVietTat: 'QS', TenQuan: 'Quế Sơn'},
      {MSQuan: 4414, TenQuanVietTat: 'TK', TenQuan: 'Tam Kỳ'},
      {MSQuan: 4415, TenQuanVietTat: 'TG', TenQuan: 'Tây Giang'},
      {MSQuan: 4416, TenQuanVietTat: 'TB', TenQuan: 'Thăng Bình'},
      {MSQuan: 4417, TenQuanVietTat: 'TP', TenQuan: 'Tiên Phước'},
    ],
  },
  {
    MSTinh: 45,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Quảng Ngãi',
    Quan: [
      {MSQuan: 4500, TenQuanVietTat: 'BT', TenQuan: 'Ba Tơ'},
      {MSQuan: 4501, TenQuanVietTat: 'BS', TenQuan: 'Bình Sơn'},
      {MSQuan: 4502, TenQuanVietTat: 'DP', TenQuan: 'Đức Phổ'},
      {MSQuan: 4503, TenQuanVietTat: 'LS', TenQuan: 'Lý Sơn'},
      {MSQuan: 4504, TenQuanVietTat: 'ML', TenQuan: 'Minh Long'},
      {MSQuan: 4505, TenQuanVietTat: 'MD', TenQuan: 'Mộ Đức'},
      {MSQuan: 4506, TenQuanVietTat: 'NH', TenQuan: 'Nghĩa Hành'},
      {MSQuan: 4507, TenQuanVietTat: 'QN', TenQuan: 'Quảng Ngãi'},
      {MSQuan: 4508, TenQuanVietTat: 'SH', TenQuan: 'Sơn Hà'},
      {MSQuan: 4509, TenQuanVietTat: 'STy', TenQuan: 'Sơn Tây'},
      {MSQuan: 4510, TenQuanVietTat: 'ST', TenQuan: 'Sơn Tịnh'},
      {MSQuan: 4511, TenQuanVietTat: 'TT', TenQuan: 'Tây Trà'},
      {MSQuan: 4512, TenQuanVietTat: 'TB', TenQuan: 'Trà Bồng'},
      {MSQuan: 4513, TenQuanVietTat: 'TN', TenQuan: 'Tư Nghĩa'},
    ],
  },
  {
    MSTinh: 46,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Quảng Ninh',
    Quan: [
      {MSQuan: 4600, TenQuanVietTat: 'BC', TenQuan: 'Ba Chẽ'},
      {MSQuan: 4601, TenQuanVietTat: 'BL', TenQuan: 'Bình Liêu'},
      {MSQuan: 4602, TenQuanVietTat: 'CP', TenQuan: 'Cẩm Phả'},
      {MSQuan: 4603, TenQuanVietTat: 'CT', TenQuan: 'Cô Tô'},
      {MSQuan: 4604, TenQuanVietTat: 'DH', TenQuan: 'Đầm Hà'},
      {MSQuan: 4605, TenQuanVietTat: 'DT', TenQuan: 'Đông Triều'},
      {MSQuan: 4606, TenQuanVietTat: 'HL', TenQuan: 'Hạ Long'},
      {MSQuan: 4607, TenQuanVietTat: 'HH', TenQuan: 'Hải Hà'},
      {MSQuan: 4608, TenQuanVietTat: 'HB', TenQuan: 'Hoành Bồ'},
      {MSQuan: 4609, TenQuanVietTat: 'MC', TenQuan: 'Móng Cái'},
      {MSQuan: 4610, TenQuanVietTat: 'QY', TenQuan: 'Quảng Yên'},
      {MSQuan: 4611, TenQuanVietTat: 'TY', TenQuan: 'Tiên Yên'},
      {MSQuan: 4612, TenQuanVietTat: 'UB', TenQuan: 'Uông Bí'},
      {MSQuan: 4613, TenQuanVietTat: 'VD', TenQuan: 'Vân Đồn'},
    ],
  },
  {
    MSTinh: 47,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Quảng Trị',
    Quan: [
      {MSQuan: 4700, TenQuanVietTat: 'CL', TenQuan: 'Cam Lộ'},
      {MSQuan: 4701, TenQuanVietTat: 'CC', TenQuan: 'Cồn Cỏ'},
      {MSQuan: 4702, TenQuanVietTat: 'DK', TenQuan: 'Đa Krông'},
      {MSQuan: 4703, TenQuanVietTat: 'DH', TenQuan: 'Đông Hà'},
      {MSQuan: 4704, TenQuanVietTat: 'GL', TenQuan: 'Gio Linh'},
      {MSQuan: 4705, TenQuanVietTat: 'HL', TenQuan: 'Hải Lăng'},
      {MSQuan: 4706, TenQuanVietTat: 'HH', TenQuan: 'Hướng Hóa'},
      {MSQuan: 4707, TenQuanVietTat: 'QT', TenQuan: 'Quảng Trị'},
      {MSQuan: 4708, TenQuanVietTat: 'TP', TenQuan: 'Triệu Phong'},
      {MSQuan: 4709, TenQuanVietTat: 'VL', TenQuan: 'Vĩnh Linh'},
    ],
  },
  {
    MSTinh: 48,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Sóc Trăng',
    Quan: [
      {MSQuan: 4800, TenQuanVietTat: 'ST', TenQuan: 'Thành phố Sóc Trăng'},
      {MSQuan: 4801, TenQuanVietTat: 'KS', TenQuan: 'Kế Sách'},
      {MSQuan: 4802, TenQuanVietTat: 'MT', TenQuan: 'Mỹ Tú'},
      {MSQuan: 4803, TenQuanVietTat: 'MX', TenQuan: 'Mỹ Xuyên'},
      {MSQuan: 4804, TenQuanVietTat: 'TT', TenQuan: 'Thạnh Trị'},
      {MSQuan: 4805, TenQuanVietTat: 'LP', TenQuan: 'Long Phú'},
      {MSQuan: 4806, TenQuanVietTat: 'VC', TenQuan: 'Thị xã Vĩnh Châu'},
      {MSQuan: 4807, TenQuanVietTat: 'CLD', TenQuan: 'Cù Lao Dung'},
      {MSQuan: 4808, TenQuanVietTat: 'NN', TenQuan: 'Ngã Năm'},
      {MSQuan: 4809, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 4810, TenQuanVietTat: 'TD', TenQuan: 'Trần Đề'},
    ],
  },
  {
    MSTinh: 49,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Sơn La',
    Quan: [
      {MSQuan: 4900, TenQuanVietTat: 'BY', TenQuan: 'Bắc Yên'},
      {MSQuan: 4901, TenQuanVietTat: 'MS', TenQuan: 'Mai Sơn'},
      {MSQuan: 4902, TenQuanVietTat: 'MC', TenQuan: 'Mộc Châu'},
      {MSQuan: 4903, TenQuanVietTat: 'ML', TenQuan: 'Mường La'},
      {MSQuan: 4904, TenQuanVietTat: 'PY', TenQuan: 'Phù Yên'},
      {MSQuan: 4905, TenQuanVietTat: 'QN', TenQuan: 'Quỳnh Nhai'},
      {MSQuan: 4906, TenQuanVietTat: 'SL', TenQuan: 'Sơn La'},
      {MSQuan: 4907, TenQuanVietTat: 'SM', TenQuan: 'Sông Mã'},
      {MSQuan: 4908, TenQuanVietTat: 'SC', TenQuan: 'Sốp Cộp'},
      {MSQuan: 4909, TenQuanVietTat: 'TC', TenQuan: 'Thuận Châu'},
      {MSQuan: 4910, TenQuanVietTat: 'VH', TenQuan: 'Vân Hồ'},
      {MSQuan: 4911, TenQuanVietTat: 'YC', TenQuan: 'Yên Châu'},
    ],
  },
  {
    MSTinh: 50,
    Mien: 'ĐÔNG NAM BỘ',
    TenTinh: 'Tây Ninh',
    Quan: [
      {MSQuan: 5000, TenQuanVietTat: 'BC', TenQuan: 'Bến Cầu'},
      {MSQuan: 5001, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 5002, TenQuanVietTat: 'DMC', TenQuan: 'Dương Minh Châu'},
      {MSQuan: 5003, TenQuanVietTat: 'GD', TenQuan: 'Gò Dầu'},
      {MSQuan: 5004, TenQuanVietTat: 'HT', TenQuan: 'Hòa Thành'},
      {MSQuan: 5005, TenQuanVietTat: 'TB', TenQuan: 'Tân Biên'},
      {MSQuan: 5006, TenQuanVietTat: 'TC', TenQuan: 'Tân Châu'},
      {MSQuan: 5007, TenQuanVietTat: 'TN', TenQuan: 'Tây Ninh'},
      {MSQuan: 5008, TenQuanVietTat: 'TBg', TenQuan: 'Trảng Bàng'},
    ],
  },
  {
    MSTinh: 51,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Thái Bình',
    Quan: [
      {MSQuan: 5100, TenQuanVietTat: 'DH', TenQuan: 'Đông Hưng'},
      {MSQuan: 5101, TenQuanVietTat: 'HH', TenQuan: 'Hưng Hà'},
      {MSQuan: 5102, TenQuanVietTat: 'KX', TenQuan: 'Kiến Xương'},
      {MSQuan: 5103, TenQuanVietTat: 'QP', TenQuan: 'Quỳnh Phụ'},
      {MSQuan: 5104, TenQuanVietTat: 'TB', TenQuan: 'Thái Bình'},
      {MSQuan: 5105, TenQuanVietTat: 'TT', TenQuan: 'Thái Thụy'},
      {MSQuan: 5106, TenQuanVietTat: 'TH', TenQuan: 'Tiền Hải'},
      {MSQuan: 5107, TenQuanVietTat: 'VT', TenQuan: 'Vũ Thư'},
    ],
  },
  {
    MSTinh: 52,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Thái Nguyên',
    Quan: [
      {MSQuan: 5200, TenQuanVietTat: 'DT', TenQuan: 'Đại Từ'},
      {MSQuan: 5201, TenQuanVietTat: 'DiH', TenQuan: 'Định Hóa'},
      {MSQuan: 5202, TenQuanVietTat: 'DH', TenQuan: 'Đồng Hỷ'},
      {MSQuan: 5203, TenQuanVietTat: 'PY', TenQuan: 'Phổ Yên'},
      {MSQuan: 5204, TenQuanVietTat: 'PB', TenQuan: 'Phú Bình'},
      {MSQuan: 5205, TenQuanVietTat: 'PL', TenQuan: 'Phú Lương'},
      {MSQuan: 5206, TenQuanVietTat: 'SC', TenQuan: 'Sông Công'},
      {MSQuan: 5207, TenQuanVietTat: 'TN', TenQuan: 'Thái Nguyên'},
      {MSQuan: 5208, TenQuanVietTat: 'VN', TenQuan: 'Võ Nhai'},
    ],
  },
  {
    MSTinh: 53,
    Mien: 'MIỀN TRUNG',
    TenTinh: 'Thanh Hóa',
    Quan: [
      {MSQuan: 5300, TenQuanVietTat: 'BT', TenQuan: 'Bá Thước'},
      {MSQuan: 5301, TenQuanVietTat: 'BS', TenQuan: 'Bỉm Sơn'},
      {MSQuan: 5302, TenQuanVietTat: 'CT', TenQuan: 'Cẩm Thủy'},
      {MSQuan: 5303, TenQuanVietTat: 'DS', TenQuan: 'Đông Sơn'},
      {MSQuan: 5304, TenQuanVietTat: 'HT', TenQuan: 'Hà Trung'},
      {MSQuan: 5305, TenQuanVietTat: 'HL', TenQuan: 'Hậu Lộc'},
      {MSQuan: 5306, TenQuanVietTat: 'HH', TenQuan: 'Hoằng Hóa'},
      {MSQuan: 5307, TenQuanVietTat: 'LC', TenQuan: 'Lang Chánh'},
      {MSQuan: 5308, TenQuanVietTat: 'ML', TenQuan: 'Mường Lát'},
      {MSQuan: 5309, TenQuanVietTat: 'NS', TenQuan: 'Nga Sơn'},
      {MSQuan: 5310, TenQuanVietTat: 'NL', TenQuan: 'Ngọc Lặc'},
      {MSQuan: 5311, TenQuanVietTat: 'NT', TenQuan: 'Như Thanh'},
      {MSQuan: 5312, TenQuanVietTat: 'NX', TenQuan: 'Như Xuân'},
      {MSQuan: 5313, TenQuanVietTat: 'NC', TenQuan: 'Nông Cống'},
      {MSQuan: 5314, TenQuanVietTat: 'QH', TenQuan: 'Quan Hóa'},
      {MSQuan: 5315, TenQuanVietTat: 'QS', TenQuan: 'Quan Sơn'},
      {MSQuan: 5316, TenQuanVietTat: 'QX', TenQuan: 'Quảng Xương'},
      {MSQuan: 5317, TenQuanVietTat: 'SS', TenQuan: 'Sầm Sơn'},
      {MSQuan: 5318, TenQuanVietTat: 'TT', TenQuan: 'Thạch Thành'},
      {MSQuan: 5319, TenQuanVietTat: 'TaH', TenQuan: 'Thanh Hóa'},
      {MSQuan: 5320, TenQuanVietTat: 'TH', TenQuan: 'Thiệu Hóa'},
      {MSQuan: 5321, TenQuanVietTat: 'TX', TenQuan: 'Thọ Xuân'},
      {MSQuan: 5322, TenQuanVietTat: 'ThX', TenQuan: 'Thường Xuân'},
      {MSQuan: 5323, TenQuanVietTat: 'TG', TenQuan: 'Tĩnh Gia'},
      {MSQuan: 5324, TenQuanVietTat: 'TS', TenQuan: 'Triệu Sơn'},
      {MSQuan: 5325, TenQuanVietTat: 'VL', TenQuan: 'Vĩnh Lộc'},
      {MSQuan: 5326, TenQuanVietTat: 'YD', TenQuan: 'Yên Định'},
    ],
  },
  {
    MSTinh: 54,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Tiền Giang',
    Quan: [
      {MSQuan: 5400, TenQuanVietTat: 'MT', TenQuan: 'Thành phố Mỹ Tho'},
      {MSQuan: 5401, TenQuanVietTat: 'GC', TenQuan: 'Thị xã Gò Công'},
      {MSQuan: 5402, TenQuanVietTat: 'CB', TenQuan: 'Cái Bè'},
      {MSQuan: 5403, TenQuanVietTat: 'CL', TenQuan: 'Cai Lậy'},
      {MSQuan: 5404, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 5405, TenQuanVietTat: 'CG', TenQuan: 'Chợ Gạo'},
      {MSQuan: 5406, TenQuanVietTat: 'GCT', TenQuan: 'Gò Công Tây'},
      {MSQuan: 5407, TenQuanVietTat: 'GCD', TenQuan: 'Gò Công Đông'},
      {MSQuan: 5408, TenQuanVietTat: 'TP', TenQuan: 'Tân Phước'},
      {MSQuan: 5409, TenQuanVietTat: 'PD', TenQuan: 'Tân Phú Đông'},
    ],
  },
  {
    MSTinh: 55,
    Mien: 'TP.HCM',
    TenTinh: 'Hồ Chí Minh',
    Quan: [
      {MSQuan: 5500, TenQuanVietTat: '1', TenQuan: 'Quận 1'},
      {MSQuan: 5501, TenQuanVietTat: '12', TenQuan: 'Quận 12'},
      {MSQuan: 5502, TenQuanVietTat: 'TD', TenQuan: 'Thủ Đức'},
      {MSQuan: 5503, TenQuanVietTat: '9', TenQuan: 'Quận 9'},
      {MSQuan: 5504, TenQuanVietTat: 'GV', TenQuan: 'Gò Vấp'},
      {MSQuan: 5505, TenQuanVietTat: 'BTH', TenQuan: 'Bình Thạnh'},
      {MSQuan: 5506, TenQuanVietTat: 'TB', TenQuan: 'Tân Bình'},
      {MSQuan: 5507, TenQuanVietTat: 'TP', TenQuan: 'Tân Phú'},
      {MSQuan: 5508, TenQuanVietTat: 'PN', TenQuan: 'Phú Nhuận'},
      {MSQuan: 5509, TenQuanVietTat: '2', TenQuan: 'Quận 2'},
      {MSQuan: 5510, TenQuanVietTat: '3', TenQuan: 'Quận 3'},
      {MSQuan: 5511, TenQuanVietTat: '10', TenQuan: 'Quận 10'},
      {MSQuan: 5512, TenQuanVietTat: '11', TenQuan: 'Quận 11'},
      {MSQuan: 5513, TenQuanVietTat: '4', TenQuan: 'Quận 4'},
      {MSQuan: 5514, TenQuanVietTat: '5', TenQuan: 'Quận 5'},
      {MSQuan: 5515, TenQuanVietTat: '6', TenQuan: 'Quận 6'},
      {MSQuan: 5516, TenQuanVietTat: '8', TenQuan: 'Quận 8'},
      {MSQuan: 5517, TenQuanVietTat: 'BTA', TenQuan: 'Bình Tân'},
      {MSQuan: 5518, TenQuanVietTat: '7', TenQuan: 'Quận 7'},
      {MSQuan: 5519, TenQuanVietTat: 'CC', TenQuan: 'Củ Chi'},
      {MSQuan: 5520, TenQuanVietTat: 'HM', TenQuan: 'Hóc Môn'},
      {MSQuan: 5521, TenQuanVietTat: 'BC', TenQuan: 'Bình Chánh'},
      {MSQuan: 5522, TenQuanVietTat: 'NB', TenQuan: 'Nhà Bè'},
      {MSQuan: 5523, TenQuanVietTat: 'CG', TenQuan: 'Cần Giờ'},
    ],
  },
  {
    MSTinh: 56,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Trà Vinh',
    Quan: [
      {MSQuan: 5600, TenQuanVietTat: 'TV', TenQuan: 'Thành phố Trà Vinh'},
      {MSQuan: 5601, TenQuanVietTat: 'CL', TenQuan: 'Càng Long'},
      {MSQuan: 5602, TenQuanVietTat: 'CK', TenQuan: 'Cầu Kè'},
      {MSQuan: 5603, TenQuanVietTat: 'TC', TenQuan: 'Tiểu Cần'},
      {MSQuan: 5604, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 5605, TenQuanVietTat: 'TCu', TenQuan: 'Trà Cú'},
      {MSQuan: 5606, TenQuanVietTat: 'CN', TenQuan: 'Cầu Ngang'},
      {MSQuan: 5607, TenQuanVietTat: 'DH', TenQuan: 'Duyên Hải'},
    ],
  },
  {
    MSTinh: 57,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Tuyên Quang',
    Quan: [
      {MSQuan: 5700, TenQuanVietTat: 'CH', TenQuan: 'Chiêm Hóa'},
      {MSQuan: 5701, TenQuanVietTat: 'HY', TenQuan: 'Hàm Yên'},
      {MSQuan: 5702, TenQuanVietTat: 'LB', TenQuan: 'Lâm Bình'},
      {MSQuan: 5703, TenQuanVietTat: 'NH', TenQuan: 'Na Hang'},
      {MSQuan: 5704, TenQuanVietTat: 'SD', TenQuan: 'Sơn Dương'},
      {MSQuan: 5705, TenQuanVietTat: 'TQ', TenQuan: 'Tuyên Quang'},
      {MSQuan: 5706, TenQuanVietTat: 'Ý', TenQuan: 'Yên Sơn'},
    ],
  },
  {
    MSTinh: 58,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Vĩnh Long',
    Quan: [
      {MSQuan: 5800, TenQuanVietTat: 'TPVL', TenQuan: 'Thành phố Vĩnh Long'},
      {MSQuan: 5801, TenQuanVietTat: 'LH', TenQuan: 'Long Hồ'},
      {MSQuan: 5802, TenQuanVietTat: 'MT', TenQuan: 'Mang Thít'},
      {MSQuan: 5803, TenQuanVietTat: 'BM', TenQuan: 'Bình Minh'},
      {MSQuan: 5804, TenQuanVietTat: 'TB', TenQuan: 'Tam Bình'},
      {MSQuan: 5805, TenQuanVietTat: 'TO', TenQuan: 'Trà Ôn'},
      {MSQuan: 5806, TenQuanVietTat: 'VL', TenQuan: 'Vũng Liêm'},
      {MSQuan: 5807, TenQuanVietTat: 'BT', TenQuan: 'Bình Tân'},
    ],
  },
  {
    MSTinh: 59,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Vĩnh Phúc',
    Quan: [
      {MSQuan: 5900, TenQuanVietTat: 'BX', TenQuan: 'Bình Xuyên'},
      {MSQuan: 5901, TenQuanVietTat: 'LT', TenQuan: 'Lập Thạch'},
      {MSQuan: 5902, TenQuanVietTat: 'PY', TenQuan: 'Phúc Yên'},
      {MSQuan: 5903, TenQuanVietTat: 'SL', TenQuan: 'Sông Lô'},
      {MSQuan: 5904, TenQuanVietTat: 'TD', TenQuan: 'Tam Đảo'},
      {MSQuan: 5905, TenQuanVietTat: 'TD', TenQuan: 'Tam Dương'},
      {MSQuan: 5906, TenQuanVietTat: 'VT', TenQuan: 'Vĩnh Tường'},
      {MSQuan: 5907, TenQuanVietTat: 'VY', TenQuan: 'Vĩnh Yên'},
      {MSQuan: 5908, TenQuanVietTat: 'YL', TenQuan: 'Yên Lạc'},
    ],
  },
  {
    MSTinh: 60,
    Mien: 'ĐÔNG NAM BỘ',
    TenTinh: 'Bà Rịa-Vũng Tàu',
    Quan: [
      {MSQuan: 6000, TenQuanVietTat: 'VT', TenQuan: 'Thành phố Vũng Tàu'},
      {MSQuan: 6001, TenQuanVietTat: 'BR', TenQuan: 'Thị xã Bà Rịa'},
      {MSQuan: 6002, TenQuanVietTat: 'XM', TenQuan: 'Xuyên Mộc'},
      {MSQuan: 6003, TenQuanVietTat: 'LD', TenQuan: 'Long Điền'},
      {MSQuan: 6004, TenQuanVietTat: 'CD', TenQuan: 'Côn Đảo'},
      {MSQuan: 6005, TenQuanVietTat: 'TT', TenQuan: 'Tân Thành'},
      {MSQuan: 6006, TenQuanVietTat: 'CDu', TenQuan: 'Châu Đức'},
      {MSQuan: 6007, TenQuanVietTat: 'DD', TenQuan: 'Đất Đỏ'},
    ],
  },
  {
    MSTinh: 61,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Yên Bái',
    Quan: [
      {MSQuan: 6100, TenQuanVietTat: 'LY', TenQuan: 'Lục Yên'},
      {MSQuan: 6101, TenQuanVietTat: 'MCC', TenQuan: 'Mù Căng Chải'},
      {MSQuan: 6102, TenQuanVietTat: 'NL', TenQuan: 'Nghĩa Lộ'},
      {MSQuan: 6103, TenQuanVietTat: 'TT', TenQuan: 'Trạm Tấu'},
      {MSQuan: 6104, TenQuanVietTat: 'TY', TenQuan: 'Trấn Yên'},
      {MSQuan: 6105, TenQuanVietTat: 'VC', TenQuan: 'Văn Chấn'},
      {MSQuan: 6106, TenQuanVietTat: 'VY', TenQuan: 'Văn Yên'},
      {MSQuan: 6107, TenQuanVietTat: 'YB', TenQuan: 'Yên Bái'},
      {MSQuan: 6108, TenQuanVietTat: 'YBi', TenQuan: 'Yên Bình'},
    ],
  },
  {
    MSTinh: 62,
    Mien: 'MIỀN TÂY',
    TenTinh: 'Hậu Giang',
    Quan: [
      {MSQuan: 6200, TenQuanVietTat: 'VT', TenQuan: 'Thành phố Vị Thanh'},
      {MSQuan: 6201, TenQuanVietTat: 'VTh', TenQuan: 'Vị Thuỷ'},
      {MSQuan: 6202, TenQuanVietTat: 'LM', TenQuan: 'Long Mỹ'},
      {MSQuan: 6203, TenQuanVietTat: 'PH', TenQuan: 'Phụng Hiệp'},
      {MSQuan: 6204, TenQuanVietTat: 'CT', TenQuan: 'Châu Thành'},
      {MSQuan: 6205, TenQuanVietTat: 'CTA', TenQuan: 'Châu Thành A'},
      {MSQuan: 6206, TenQuanVietTat: 'NB', TenQuan: 'Thị xã Ngã Bảy'},
    ],
  },
  {
    MSTinh: 63,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Đăk Nông',
    Quan: [
      {MSQuan: 6300, TenQuanVietTat: 'CJ', TenQuan: 'Cư Jút'},
      {MSQuan: 6301, TenQuanVietTat: 'DG', TenQuan: 'Đăk Glong'},
      {MSQuan: 6302, TenQuanVietTat: 'DM', TenQuan: 'Đăk Mil'},
      {MSQuan: 6303, TenQuanVietTat: 'DR', TenQuan: "Đăk R'Lấp"},
      {MSQuan: 6304, TenQuanVietTat: 'DS', TenQuan: 'Đăk Song'},
      {MSQuan: 6305, TenQuanVietTat: 'GN', TenQuan: 'Gia Nghĩa'},
      {MSQuan: 6306, TenQuanVietTat: 'KN', TenQuan: 'Krông Nô'},
      {MSQuan: 6307, TenQuanVietTat: 'TD', TenQuan: 'Tuy Đức'},
    ],
  },
  {
    MSTinh: 64,
    Mien: 'MIỀN BẮC',
    TenTinh: 'Điện Biên',
    Quan: [
      {MSQuan: 6400, TenQuanVietTat: 'DB', TenQuan: 'Điện Biên'},
      {MSQuan: 6401, TenQuanVietTat: 'DBD', TenQuan: 'Điện Biên Đông'},
      {MSQuan: 6402, TenQuanVietTat: 'DBP', TenQuan: 'Điện Biên Phủ'},
      {MSQuan: 6403, TenQuanVietTat: 'MA', TenQuan: 'Mường Ảng'},
      {MSQuan: 6404, TenQuanVietTat: 'MC', TenQuan: 'Mường Chà'},
      {MSQuan: 6405, TenQuanVietTat: 'ML', TenQuan: 'Mường Lay'},
      {MSQuan: 6406, TenQuanVietTat: 'MN', TenQuan: 'Mường Nhé'},
      {MSQuan: 6407, TenQuanVietTat: 'NP', TenQuan: 'Nậm Pồ'},
      {MSQuan: 6408, TenQuanVietTat: 'TC', TenQuan: 'Tủa Chùa'},
      {MSQuan: 6409, TenQuanVietTat: 'TG', TenQuan: 'Tuần Giáo'},
    ],
  },
];
